# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_constraint <- function(delta_tau, phi) {
    .Call(`_iclogcondist_compute_constraint`, delta_tau, phi)
}

find_re_phi_cpp <- function(tilde_phi, is, qsi) {
    .Call(`_iclogcondist_find_re_phi_cpp`, tilde_phi, is, qsi)
}

compute_first_second_diag_order_phi <- function(weight, phi, li, ri, L_Rc, Lc_R, Lc_Rc) {
    .Call(`_iclogcondist_compute_first_second_diag_order_phi`, weight, phi, li, ri, L_Rc, Lc_R, Lc_Rc)
}

compute_1st_2nd_order_tilde_cpp <- function(first_order, second_order, is, qsi) {
    .Call(`_iclogcondist_compute_1st_2nd_order_tilde_cpp`, first_order, second_order, is, qsi)
}

